from PIL import Image, ImageDraw, ImageFont, ImageChops
from fontTools.ttLib import TTFont
import sys
import argparse

class Glyph:
    def __init__(self, c, code, width, height, xoffset, yoffset, ptr, xadvance):
        self.c = c
        self.code = code
        self.width = width
        self.height = height
        self.xoffset = xoffset
        self.yoffset = yoffset
        self.ptr = ptr
        self.xadvance = xadvance

class Kern:
    def __init__(self, first, second, amount):
        self.first = first
        self.second = second
        self.amount = amount

class FontSampler:
    def __init__(self, unicode_ranges=None, symbols=""):
        self.m_unicodeRanges = ([(0x20, 0x7e), (0xa0, 0xff)]
                                if unicode_ranges is None else unicode_ranges)
        self.m_symbols = symbols
        self.m_glyphs = {}
        self.m_data = []
        self.m_kerns = []
        self.m_uncompressed_size = 0

    def convertFont(self, font, tt_font, filename):
        characters = {}

        for start, end in self.m_unicodeRanges:
            for codepoint in range(start, end + 1):
                if not 0xd800 <= codepoint <= 0xdfff:
                    characters[codepoint] = chr(codepoint)

        for character in self.m_symbols:
            characters[ord(character)] = character

        for codepoint in sorted(characters):
            self.convertGlyph(font, characters[codepoint])

        # Calculate kerning for each pair of glyphs
        self.calcAllKerns(tt_font)

        fontName = font.getname()[0].replace(" ", "_")
        with open(filename, 'w', encoding='utf-8', newline='\n') as fout:
            fout.write("// Output generated by Portable Type Engine's Font Tool\n")
            fout.write("// FONT: " + font.getname()[0] + "\n")
            fout.write("// Font Pixel Height Sampled: " + str(font.size) + "\n")
            fout.write("// Character codes: Unicode code points\n\n")
            # Calculate total data size: image data + glyph data + kern data
            total_bytes = len(self.m_data) + (28 * len(self.m_glyphs)) + (12 * len(self.m_kerns))
            fout.write("// Font data size: " + str(len(self.m_data) + (28 * len(self.m_glyphs))) + " bytes\n")
            fout.write("// Font kerning table: " + str(12 * len(self.m_kerns)) + " bytes\n")
            fout.write("// Total font data size: " + str(total_bytes) + " bytes (" + format(total_bytes/1024.0,".1f") + "Kb)\n\n")

            fout.write("#include \"pte.h\"\n\n")

            # Output glyphs
            fout.write("static const pte_glyph " + fontName + "_glyphs[" + str(len(self.m_glyphs)) + "] = {\n")
            for code in sorted(self.m_glyphs):
                g = self.m_glyphs[code]
                fout.write(" { " + str(code) + "," + str(g.width) + "," + str(g.height) + ","
                        + str(g.xoffset) + "," + str(g.yoffset) + "," + str(g.xadvance) + ","
                        + str(g.ptr) + " },\n")
            fout.write("};\n\n")

            # Output data array
            fout.write("static const unsigned char " + fontName + "_data[" + str(len(self.m_data)) + "] = {")
            count = 0
            for i, val in enumerate(self.m_data):
                if count % 50 == 0:
                    fout.write("\n ")
                fout.write(str(val))
                if i != len(self.m_data) - 1:
                    fout.write(",")
                count += 1
            fout.write("\n};\n\n")

            # Output kerning data if available
            if self.m_kerns:
                fout.write("static const pte_kern " + fontName + "_kerns[" + str(len(self.m_kerns)) + "] = {\n")
                for k in self.m_kerns:
                    fout.write(" { " + str(k.first) + "," + str(k.second) + "," + str(self.scaleKern(k.amount, font, tt_font)) + " },\n")
                fout.write("};\n\n")

            # Output font structure
            fout.write("static pte_base_font f =\n")
            fout.write(" { " + str(font.size) + ", "
                    + fontName + "_data, "
                    + str(len(self.m_glyphs)) + ","
                    + fontName + "_glyphs, ")
            if self.m_kerns:
                fout.write(str(len(self.m_kerns)) + ","
                        + fontName + "_kerns, ")
            else:
                fout.write("0,0,")

            # For line spacing, we use font.getsize on a capital letter
            ascent, descent = font.getmetrics()
            lineSpacing = ascent + descent
            # lineSpacing = self.get_text_size(font, "M")[1]
            fout.write(str(lineSpacing) + ", " + str(font.size) + " };\n\n")
            fout.write("pte_base_font *get_" + fontName + str(font.size) + "()\n")
            fout.write("{\n    return &f;\n}\n")

    def output_pixel(self, run_of_on, pixels_so_far, pixel):
        if run_of_on:
            pixel |= (pixels_so_far << 4)
        else:
            pixel |= pixels_so_far
            self.m_data.append(pixel)
            pixel = 0
        pixels_so_far = 0
        run_of_on = not run_of_on
        return run_of_on, pixels_so_far, pixel

    def val(self, c):
        return ord(c)

    def convertGlyph(self, font, c):
        # Get approximate text size using Pillow's font measurement
        w, h = self.get_text_size(font, c)
        img_width = w * 2 if w > 0 else 1
        img_height = h * 4 if h > 0 else 1

        # Create a white background image and draw the character in black.
        image = Image.new("RGB", (img_width, img_height), "white")
        draw = ImageDraw.Draw(image)
        baseline = h * 3
        draw.text((0, baseline), c, fill="black", font=font, anchor="ls")

        # Determine the bounding box of non-white (black) pixels.
        # Invert image colors so that text becomes non-zero then use getbbox().
        inv = ImageChops.invert(image)
        bbox = inv.getbbox()
        if bbox is None:
            bbox = (0, 0, 0, 0)

        left, top, right, bottom = bbox
        width = (right - left) 
        height = (bottom - top)
        xoffset = left
        yoffset = baseline - top
        xadvance = self.get_text_size(font, c)[0]
        code = self.val(c)
        ptr = len(self.m_data)
        g = Glyph(c, code, width, height, xoffset, yoffset, ptr, xadvance)
        self.m_glyphs[code] = g

        self.m_uncompressed_size = ((width + 7) // 8) * height

        pixel = 0
        run_of_on = False
        pixels_so_far = 0

        # Process pixels in the bounding box.
        for y in range(top, bottom):
            for x in range(left, right):
                last_pixel = (x == right - 1 and y == bottom - 1)
                # Check if pixel is more than 50% black
                # Note: We are using RGB mode so black is (0, 0, 0)
                t = image.getpixel((x, y))
                on = t[0] < 128
                if run_of_on != on:
                    run_of_on, pixels_so_far, pixel = self.output_pixel(run_of_on, pixels_so_far, pixel)
                pixels_so_far += 1
                if pixels_so_far == 15:
                    run_of_on, pixels_so_far, pixel = self.output_pixel(run_of_on, pixels_so_far, pixel)
                if last_pixel and pixels_so_far != 0:
                    run_of_on, pixels_so_far, pixel = self.output_pixel(run_of_on, pixels_so_far, pixel)
                if last_pixel and run_of_on:
                    run_of_on, pixels_so_far, pixel = self.output_pixel(run_of_on, pixels_so_far, pixel)

    def calcAllKerns(self, tt_font):
        # Map glyph names to the Unicode code points emitted in the glyph table.
        cmap = tt_font.getBestCmap()
        glyph_codes = {}
        for code, glyph in self.m_glyphs.items():
            glyph_name = cmap.get(ord(glyph.c))
            if glyph_name:
                glyph_codes.setdefault(glyph_name, []).append(code)

        kerns = {}

        def add_kern(first_name, second_name, amount):
            if not amount:
                return
            for first in glyph_codes.get(first_name, []):
                for second in glyph_codes.get(second_name, []):
                    kerns[(first, second)] = amount

        # Process legacy 'kern' table if available.
        if 'kern' in tt_font:
            for subtable in tt_font['kern'].kernTables:
                for (glyph_name_a, glyph_name_b), amount in subtable.kernTable.items():
                    add_kern(glyph_name_a, glyph_name_b, amount)

        # GPOS data is processed even when a legacy kern table is present. GPOS
        # values replace duplicate legacy pairs because they are the newer data.
        if 'GPOS' in tt_font:
            gpos_table = tt_font['GPOS'].table
            if hasattr(gpos_table, 'LookupList'):
                lookup_indexes = None
                if getattr(gpos_table, 'FeatureList', None):
                    lookup_indexes = {
                        index
                        for record in gpos_table.FeatureList.FeatureRecord
                        if record.FeatureTag == 'kern'
                        for index in record.Feature.LookupListIndex
                    }
                lookups = enumerate(gpos_table.LookupList.Lookup)
                for lookup_index, lookup in lookups:
                    if lookup_indexes is not None and lookup_index not in lookup_indexes:
                        continue
                    for subtable in lookup.SubTable:
                        lookup_type = lookup.LookupType
                        if lookup_type == 9 and subtable.ExtensionLookupType == 2:
                            lookup_type = subtable.ExtensionLookupType
                            subtable = subtable.ExtSubTable
                        if lookup_type != 2:
                            continue
                        if subtable.Format == 1:
                            # Format 1: Glyph-specific pair sets.
                            coverage = subtable.Coverage.glyphs
                            for i, pairSet in enumerate(subtable.PairSet):
                                firstName = coverage[i]
                                if firstName not in glyph_codes:
                                    continue
                                for record in pairSet.PairValueRecord:
                                    value1 = (record.Value1.XAdvance
                                        if record.Value1 and hasattr(record.Value1, "XAdvance")
                                        else 0)
                                    add_kern(firstName, record.SecondGlyph, value1)
                        elif subtable.Format == 2:
                            # Format 2: expand class pairs only for emitted glyphs.
                            class1_defs = subtable.ClassDef1.classDefs
                            class2_defs = subtable.ClassDef2.classDefs
                            for firstName in subtable.Coverage.glyphs:
                                if firstName not in glyph_codes:
                                    continue
                                class1 = class1_defs.get(firstName, 0)
                                if class1 >= len(subtable.Class1Record):
                                    continue
                                class2_records = subtable.Class1Record[class1].Class2Record
                                for secondName in glyph_codes:
                                    class2 = class2_defs.get(secondName, 0)
                                    if class2 >= len(class2_records):
                                        continue
                                    value = class2_records[class2].Value1
                                    amount = (value.XAdvance
                                        if value and hasattr(value, "XAdvance") else 0)
                                    add_kern(firstName, secondName, amount)

        self.m_kerns = [Kern(first, second, amount)
                        for (first, second), amount in sorted(kerns.items())]
    def scaleKern(self, kern_amount, font, tt_font):
        # Get the unitsPerEm from the font's head table
        units_per_em = tt_font['head'].unitsPerEm
        # Calculate the scaling factor from design units to pixels
        scale = font.size / units_per_em
        # Return the kern value scaled to pixels (rounded to nearest int)
        return int(round(kern_amount * scale))                    
                        
    def get_text_size(self, font, text):
        bbox = font.getbbox(text)
        if bbox:
            return (bbox[2] - bbox[0], bbox[3] - bbox[1])
        return (0, 0)
    
def parse_ranges(value):
    ranges = []
    for item in value.split(','):
        item = item.strip()
        if not item:
            continue
        bounds = item.split('-', 1)
        if len(bounds) != 2:
            raise argparse.ArgumentTypeError(
                f"invalid range '{item}'; expected START-END")
        try:
            start, end = (int(bound.strip(), 0) for bound in bounds)
        except ValueError as error:
            raise argparse.ArgumentTypeError(
                f"invalid range '{item}'; values may be decimal or 0x-prefixed") from error
        if start < 0 or end > 0x10ffff or start > end:
            raise argparse.ArgumentTypeError(
                f"invalid Unicode range '{item}'")
        ranges.append((start, end))
    if not ranges:
        raise argparse.ArgumentTypeError("at least one range is required")
    return ranges


class RangeAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        ranges = list(getattr(namespace, self.dest, None) or [])
        for value in values:
            try:
                ranges.extend(parse_ranges(value))
            except argparse.ArgumentTypeError as error:
                raise argparse.ArgumentError(self, str(error)) from error
        setattr(namespace, self.dest, ranges)


def create_argument_parser():
    parser = argparse.ArgumentParser(
        description="Convert font files into C arrays for Portable Type Engine."
    )
    parser.add_argument("--font", dest="font_file", required=True,
                        help="Path to the input font file.")
    parser.add_argument("--output", dest="output_file", required=True,
                        help="Path to the output C file.")
    parser.add_argument("--range", dest="ranges", nargs="+",
        action=RangeAction, default=[], metavar="START-END[,START-END...]",
        help=("Add one or more Unicode code point ranges. Values may be decimal "
              "or 0x-prefixed; this option may be repeated."))
    parser.add_argument("--symbols", default="", metavar="TEXT",
        help="Add individual Unicode symbols, for example '€£→✓'.")
    return parser


def main(argv=None):
    args = create_argument_parser().parse_args(argv)

    font_file = args.font_file
    output_file = args.output_file
    unicode_ranges = args.ranges if args.ranges or args.symbols else None

    try:
        sample_font = ImageFont.truetype(font_file, 128)
    except IOError:
        print("Unable to load font. Please check the font file path.")
        return 1

    # Also load the font via fontTools.
    try:
        tt_font = TTFont(font_file)
    except Exception as e:
        print("Unable to load the font via fontTools:", e)
        return 1

    sampler = FontSampler(unicode_ranges=unicode_ranges, symbols=args.symbols)
    sampler.convertFont(sample_font, tt_font, output_file)
    return 0


if __name__ == '__main__':
    sys.exit(main())
